### ISSUE TITLE
Where to find the files listed in README.md?

### ISSUE THREAD

**Issue by LuizZ-CSS** [valentinhofmann/politosphere#1]
Excuse me for being new to opensource dataset accessing. I can't find the data files on the README.md, namely networks_YYYY.csv, subreddits_metadata.json, users_metadata.json, comments_YYYY-MM.bz2. Or should I apply the scripts you provided to the original dataset ([Pushshift Reddit Dataset](https://doi.org/10.5281/zenodo.3608135).)?

**Comment by valentinhofmann** [comment]
Thanks for your interest in the Reddit Politosphere! You can find all files [here](https://zenodo.org/record/5851729#.ZAXEN3bMLGI).
